### ISSUE TITLE
Getting Error after launching  launch_hw_emu.sh 

### ISSUE THREAD

**Issue by Prathmesh-shalu141** [arc-research-lab/CHARM#35]
The error is: 
[C 10:01:23.052 NotebookApp] Bad configuration encountered during initialization: No such notebook dir: ''/usr/share/example-notebooks''
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error

I also tried running the command, but it stuck after the kernel graph ran. Additionally, I have attached the screen shot.
Please provide appropriate steps for successful emulation testing 

![image](https://github.com/arc-research-lab/CHARM/assets/160479228/dd3b073f-429a-4435-b59d-9f94b21e6aac)

**Comment by Prathmesh-shalu141** [comment]
I also tried running the command but it stuck after kernel graph ran 
![image](https://github.com/arc-research-lab/CHARM/assets/160479228/c5a3e05d-93b3-4dc1-be17-28e699a4248c)

**Comment by JinmingZhuang** [comment]
1) Ignore the "Notebook" errors by pressing "enter".

2) The process you did is correct, the printed information means the program is already under simulation. However since the iteration number is 100 which is too large for this case in simulation, it needs too much time to get the result. Try below and wait for tens of minutes:

```
./hostexe mm_hw_emu.xclbin 1024 1024 1024 1 0
```

**Comment by Prathmesh-shalu141** [comment]
The output shown in the snapshot is as follows: is this the correct output?
![image](https://github.com/arc-research-lab/CHARM/assets/160479228/16a5e3a5-e0d1-4429-8cc3-681eea9a1a66)

**Comment by JinmingZhuang** [comment]
Right, this is as expected.
